const fs = require("node:fs");
const vm = require("node:vm");
const assert = require("node:assert/strict");
const ctx = vm.createContext({});
vm.runInContext(fs.readFileSync("app/static/energy-math.js", "utf8"), ctx);
const row = {period:"2026/09/07 - 2026/09/13", totalKwh:68.1};
const weekly = [{period:row.period, value:13.7}];
const daily = Array.from({length:7}, (_,i)=>({date:"2026-09-"+String(7+i).padStart(2,"0"),km:i===0?0:80}));
let m = ctx.cycleEnergyMetrics(row, weekly, daily);
assert.equal(m.complete,true);
assert.equal(m.recorded,480);
assert.ok(Math.abs(m.inferred-497.08029)<0.001);
assert.ok(Math.abs(m.remainingPct-16.8498)<0.001);
assert.ok(m.differencePct>0);
assert.equal(ctx.cycleEnergyMetrics(row,weekly,daily.slice(1)).difference,null);
assert.equal(ctx.cycleEnergyMetrics(row,[],daily).inferred,null);
assert.equal(ctx.cycleEnergyMetrics(row,[{period:"2026/08/31 - 2026/09/06",value:10}],daily).inferred,null);
assert.equal(ctx.cycleEnergyMetrics(row,weekly,daily.map(r=>({...r,km:0}))).differencePct,null);
m=ctx.cycleEnergyMetrics({...row,totalKwh:100},weekly,daily);
assert.equal(m.remainingPct,0);
assert.ok(m.excess>18);
assert.equal(ctx.cycleEnergyMetrics({...row,totalKwh:0},weekly,daily).remainingPct,100);
console.log("Energy math: all checks passed");
